typography_spectrum: 0.4000415022019297
color:
  brandColors:
    - '#00687d'
    - '#f4e3bf'
    - '#0d222a'
    - '#b14f50'
    - '#ef0058'
  brandStrength: 0.1875
  lightness: 0.9938919770065695
  saturation: 0.23792472947388887
  rhythmicContrast: 0.6986286910250783
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbb6c436-1548-47f0-ba22-a7c532d3b268.png
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Mindful Champions
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
