name: Mindful Champions
favicon: null
layout_spectrum: 0.8646852499805391
typography_spectrum: 0.4000415022019297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00687d'
    - '#f4e3bf'
    - '#0d222a'
    - '#b14f50'
    - '#ef0058'
  brandStrength: 0.1875
  lightness: 0.9938919770065695
  saturation: 0.23792472947388887
  rhythmicContrast: 0.6986286910250783
purpose: []
